// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hook": {
            "post": {
                "description": "Transforms LDAP entries and derives searches",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Process LDAP hook",
                "parameters": [
                    {
                        "description": "Hook request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.HookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HookResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.DerivedSearch": {
            "type": "object",
            "properties": {
                "baseDN": {
                    "type": "string"
                },
                "filter": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "oneshot": {
                    "type": "boolean"
                },
                "refresh": {
                    "type": "integer"
                }
            }
        },
        "main.HookRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Attributes of the entry\nrequired: true",
                    "type": "object",
                    "additionalProperties": true
                },
                "dn": {
                    "description": "Distinguished Name of the LDAP entry\nrequired: true",
                    "type": "string"
                }
            }
        },
        "main.HookResponse": {
            "type": "object",
            "properties": {
                "dependencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "derived": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.DerivedSearch"
                    }
                },
                "transformed": {
                    "$ref": "#/definitions/main.TransformedEntry"
                }
            }
        },
        "main.TransformedEntry": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "dn": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:5001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Hook Service",
	Description:      "LDAP synchronization hook for ordrd-group-x",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
