// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hook": {
            "post": {
                "description": "Processes LDAP hook payload and transforms or derives actions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "LDAP Hook",
                "parameters": [
                    {
                        "description": "Hook payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Payload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HookResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.HookResponse": {
            "type": "object",
            "properties": {
                "dependencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "derived": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.SearchSpec"
                    }
                },
                "transformed": {
                    "$ref": "#/definitions/main.Transformed"
                }
            }
        },
        "main.Payload": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "dn": {
                    "type": "string"
                }
            }
        },
        "main.SearchSpec": {
            "type": "object",
            "properties": {
                "baseDN": {
                    "type": "string"
                },
                "filter": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "oneshot": {
                    "type": "boolean"
                },
                "refresh": {
                    "type": "integer"
                }
            }
        },
        "main.Transformed": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "dn": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:5001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ordrd-group-x API",
	Description:      "Hook service for LDAP synchronization",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
